//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurulTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aksiyonlar
    {
        public int AksiyonID { get; set; }
        public int KurulID { get; set; }
        public string KriterNo { get; set; }
        public string GorusulenKonu { get; set; }
        public string MevcutDurumu { get; set; }
        public int SorumluPersNo { get; set; }
        public Nullable<System.DateTime> GundemeTarihi { get; set; }
        public Nullable<System.DateTime> HedefTarihi { get; set; }
        public Nullable<System.DateTime> IsBitisTarihi { get; set; }
        public Nullable<int> KayitSahibiPersNo { get; set; }
        public string SorumluPersoneller { get; set; }
        public string AksiyonSonucu { get; set; }
        public string Gelisme { get; set; }
        public string Sonuc { get; set; }
    
        public virtual Kurullar Kurullar { get; set; }
    }
}
