//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurulTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosyalar
    {
        public int DosyaID { get; set; }
        public int KurulID { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaYeniAdi { get; set; }
        public int YukleyenPersNo { get; set; }
        public string Aciklama { get; set; }
        public string Tur { get; set; }
    
        public virtual Kurullar Kurullar { get; set; }
    }
}
