//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurulTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Katilim
    {
        public int ID { get; set; }
        public int KurulID { get; set; }
        public System.DateTime Tarih { get; set; }
        public string PerNr { get; set; }
        public Nullable<bool> Katildi { get; set; }
    
        public virtual Kurullar Kurullar { get; set; }
    }
}
