//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurulTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurullar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurullar()
        {
            this.Aksiyonlar = new HashSet<Aksiyonlar>();
            this.Dosyalar = new HashSet<Dosyalar>();
            this.Katilim = new HashSet<Katilim>();
            this.Uyeler = new HashSet<Uyeler>();
        }
    
        public int KurulID { get; set; }
        public string Adi { get; set; }
        public int Sponsoru { get; set; }
        public int Baskani { get; set; }
        public int Raportor { get; set; }
        public string Amac { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string Gundem { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<System.DateTime> BasTarihi { get; set; }
        public string Sorumluluklar { get; set; }
        public string IlgiliUstSurec { get; set; }
        public string Politika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aksiyonlar> Aksiyonlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dosyalar> Dosyalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Katilim> Katilim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uyeler> Uyeler { get; set; }
    }
}
