//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurulTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KurullarView
    {
        public int KurulID { get; set; }
        public string KurulAdi { get; set; }
        public string RaportorAdSoyad { get; set; }
    }
}
